export const testData = [
  {
    title: "BigBuck Bunny",
    url: "http://ftp.itec.aau.at/datasets/DASHDataset2014/BigBuckBunny/1sec/BigBuckBunny_1s_simple_2014_05_09.mpd",
    cat: "Animation",
    type: "mpd",
  },
  {
    title: "Elephants Dream",
    url: "http://ftp.itec.aau.at/datasets/DASHDataset2014/ElephantsDream/15sec/ElephantsDream_15s_simple_2014_05_09.mpd",
    cat: "Animation",
    type: "mpd",
  },
  {
    title: "Blender Intro",
    url: "https://amssamples.streaming.mediaservices.windows.net/634cd01c-6822-4630-8444-8dd6279f94c6/CaminandesLlamaDrama4K.ism/manifest(format=m3u8-aapl)",
    cat: "Animation",
    type: "m3u8",
  },
  {
    title: "Of Forest And Men",
    url: "http://ftp.itec.aau.at/datasets/DASHDataset2014/OfForestAndMen/15sec/OfForestAndMen_15s_simple_2014_05_09.mpd",
    cat: "Movie",
    type: "mpd",
  },
  {
    title: "RedBull Play Streets",
    url: "http://ftp.itec.aau.at/datasets/DASHDataset2014/RedBullPlayStreets/15sec/RedBull_15s_simple_2014_05_09.mpd",
    cat: "Sport",
    type: "mpd",
  },
  {
    title: "Tears Of Steel",
    url: "http://ftp.itec.aau.at/datasets/DASHDataset2014/TearsOfSteel/15sec/TearsOfSteel_15s_simple_2014_05_09.mpd",
    cat: "Movie",
    type: "mpd",
  },
  {
    title: "The Swiss Account",
    url: "http://ftp.itec.aau.at/datasets/DASHDataset2014/TheSwissAccount/15sec/TheSwissAccount_15s_simple_2014_05_09.mpd",
    cat: "Movie",
    type: "mpd",
  },
  {
    title: "Valkaama ",
    url: "http://ftp.itec.aau.at/datasets/DASHDataset2014/Valkaama/15sec/Valkaama_15s_simple_2014_05_09.mpd",
    cat: "Movie",
    type: "mpd",
  },
  {
    title: "Parkour",
    url: "https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8",
    cat: "Documentary",
    type: "m3u8",
  },
  {
    title: "Blender Intro",
    url: "https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8",
    cat: "Animation",
    type: "m3u8",
  },
  {
    title: "Microsoft Azure Intro",
    url: "https://amssamples.streaming.mediaservices.windows.net/91492735-c523-432b-ba01-faba6c2206a2/AzureMediaServicesPromo.ism/manifest(format=m3u8-aapl)",
    cat: "Other",
    type: "m3u8",
  },
  {
    title: "Microsoft Azure Old Intro",
    url: "https://amssamples.streaming.mediaservices.windows.net/69fbaeba-8e92-4740-aedc-ce09ae945073/AzurePromo.ism/manifest(format=m3u8-aapl)",
    cat: "Other",
    type: "m3u8",
  },
  {
    title: "Dolby Vision Test Audio",
    url: "http://media.developer.dolby.com/DolbyVision_Atmos/profile8.1_DASH/p8.1.mpd",
    cat: "Other",
    type: "mpd",
  },
  {
    title: "Photography",
    url: "https://d3rlna7iyyu8wu.cloudfront.net/skip_armstrong/skip_armstrong_stereo_subs.m3u8",
    cat: "Documentary",
    type: "m3u8",
  },
  {
    title: "Live Stream #1",
    url: "https://cph-p2p-msl.akamaized.net/hls/live/2000341/test/master.m3u8",
    cat: "Live",
    type: "m3u8",
  },
  {
    title: "Live Stream #2",
    url: "https://livesim.dashif.org/livesim/chunkdur_1/ato_7/testpic4_8s/Manifest.mpd",
    cat: "Live",
    type: "mpd",
  },
  {
    title: "Audio Profile",
    url: "https://dash.akamaized.net/dash264/TestCasesUHD/2b/11/MultiRate.mpd",
    cat: "Live",
    type: "mpd",
  },
];
